%YAML 1.2
---
description: >-
  Cutsom shrinkwrap config

concrete: true

layers:
  - FVP_Base_RevC-2xAEMvA-base.yaml
  - arch/v9.3.yaml
  - tfa-base.yaml
  - dt-base.yaml
  - ns-edk2-base.yaml

build:
  tfa:
    params:
      ENABLE_FEAT_MTE2: 1
      ENABLE_SVE_FOR_NS: 1
      ENABLE_SVE_FOR_SWD: 1
      ENABLE_SME_FOR_NS: 1
      ENABLE_SME_FOR_SWD: 1
      ENABLE_SME2_FOR_NS: 1

  acpica:
    repo:
      remote: https://github.com/acpica/acpica.git
      revision: R2025_04_04

  edk2:
    repo:
      edk2:
        remote: https://github.com/tianocore/edk2.git
        revision: 8310dfa9f49bf4eff96a36291bc0028be920f60b
      edk2-platforms:
        remote: https://github.com/tianocore/edk2-platforms.git
        revision: 996c79ee0ed5236a0449b20f2bec4162ab4185fd

run:
  params:
    -C cluster0.memory_tagging_support_level: 2
    -C cluster1.memory_tagging_support_level: 2
    -C bp.dram_metadata.is_enabled: 1
