%YAML 1.2
---
description: >-
  Cutsom shrinkwrap config

concrete: true

layers:
  - FVP_Base_RevC-2xAEMvA-base.yaml
  - arch/v9.5.yaml
  - tfa-base.yaml
  - dt-base.yaml
  - ns-edk2-base.yaml

build:
  tfa:
    params:
      ENABLE_FEAT_MTE2: 1
      ENABLE_SVE_FOR_NS: 1
      ENABLE_SVE_FOR_SWD: 1
      ENABLE_SME_FOR_NS: 1
      ENABLE_SME_FOR_SWD: 1
      ENABLE_SME2_FOR_NS: 1

  acpica:
    repo:
      remote: https://github.com/acpica/acpica.git
      revision: 20250807

  edk2:
    repo:
      edk2:
        remote: https://github.com/tianocore/edk2.git
        revision: 8b3b2a64886f6ce6a987421668d1beb8ddff1e49
      edk2-platforms:
        remote: https://github.com/tianocore/edk2-platforms.git
        revision: 17893ae84e968214ee6db15bf7502531d9034260

run:
  params:
    -C cluster0.memory_tagging_support_level: 2
    -C cluster1.memory_tagging_support_level: 2
    -C bp.dram_metadata.is_enabled: 1
