patch:

  # commit_code | commit_text | inline_ascii | clear | noop
  ascii_composer/switch_key/Shift_L: noop
  ascii_composer/switch_key/Control_R: commit_code

  switcher:
    hotkeys:
    # - F4
      - Control+grave
      - Control+Shift+grave
    # - Alt+grave
